### ISSUE TITLE
[BUG] V11 Won't Load Scenes With Tokens Anymore

### ISSUE THREAD

**Issue by TheNittles** [arbron/fvtt-hp-bar#28]
**Describe the bug**
In my v11 game, after updating to 2.2.6, the canvas in any scenes with tokens will not load.

**To Reproduce**
1. Be on Foundry V11
2. Attempt to load a scene with tokens on it.
3. The canvas will not render for the scene.

**Expected behavior**
The canvas renders.

**Environment:**
 - Foundry Core Version: v11.315
 - Module Version: 2.2.6
 - Host: Forge
 - OS & Browser: Windows 11, Chrome

**Comment by Arnura** [comment]
I encountered this exact same issue today (9th September 2024), almost in the exact same circumstances as the initial report above, I am on windows 10 and do not use forge, just foundry, but otherwise all other circumstances to the above report are identical, I have used find the culprit and determined that with all other modules bar this one turned off, canvas still will not render. For now I just have to move forward without the module.

**Comment by skepickle** [comment]
Okay, I think this following patch fixes the issue:

```sh
diff --git a/scripts/drawing.mjs b/scripts/drawing.mjs
index 699f0a9..ebfeb76 100644
--- a/scripts/drawing.mjs
+++ b/scripts/drawing.mjs
@@ -1,5 +1,6 @@
 import constants from './shared/constants.mjs';
 import { defaultTheme } from "./theme.mjs";
+import * as utils from "./shared/utils.mjs";


 export class Color {
```

Basically the "drawing.mjs" file makes reference to utils, but it's not being imported... so the code fails to find anything called "utils" in that scope. With this patch, I can now load scenes with tokens on them.
